apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentci-demo-ruby-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentci-demo-ruby-kubernetes
  template:
    metadata:
      labels:
        app: fluentci-demo-ruby-kubernetes
    spec:
      imagePullSecrets:
        - name: dockerhub
      containers:
        - name: fluentci-demo-ruby-kubernetes
          image: $DOCKER_USERNAME/fluentci-demo-ruby-kubernetes:$FLUENTCI_WORKFLOW_ID

---
apiVersion: v1
kind: Service
metadata:
  name: fluentci-demo-ruby-kubernetes-lb
spec:
  selector:
    app: fluentci-demo-ruby-kubernetes
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4567
